dataset: 
  type: COCOStuff
  augmentation: randomcrop+flip
  size: 256
train_data: 
  images: /d1/rsankar/data/COCOstuff/train2017
  masks: /d1/rsankar/data/COCOstuff/train2017
  labels: [1, 2, 3, 4, 5, 6, 7]
validation_data: 
  images: /d1/rsankar/data/COCOstuff/val2017
  masks: /d1/rsankar/data/COCOstuff/val2017
  labels: [1, 2, 3, 4, 5, 6, 7]
model_params:
  gen_filts: 32
  disc_filts: 16
  activation: relu
  use_dropout: True
  final_activation: sigmoid
  n_disc_layers: 5
checkpoint_path: ./checkpoints/checkpoint-COCO/
load_last_checkpoint: True
train_params:
  loss_type: weighted_bce
  seg_alpha: 200
  gen_learning_rate: 1.e-3
  disc_learning_rate: 1.e-3
  decay_rate: 0.95
  save_freq: 5

